### PR TITLE
Matlab donna

### PR DESCRIPTION
**Pull request by donnaaboise**
Some minor changes to Matlab graphics, including fix to 'setopengl', so that it compares to lower case selection only.

### CODE REVIEW

**Comment by mandli** [comment]
This looks fine to me, I take it these are all just minor bug fixes that have built up over time?

**Comment by donnaaboise** [comment]
Yes - that’s right.  Minor changes only.  But hold off - that PR didn’t have master merged in. I’ll issue a new PR.

**Comment by donnaaboise** [comment]
Okay - I issued a new PR - But the Matlab changes are the same.

**Comment by mandli** [comment]
Where did you issue the PR to?  I only see this one still.

**Comment by donnaaboise** [comment]
I thought I issued a new PR, but it seems that I can only view it - maybe because the original PR merged with master without conflicts, so the second PR didn't do anything?   Go ahead and merge.

**Pull request merged**
