### PR TITLE
Fix format handling in `gettime` to be more general

### PR DESCRIPTION
**Pull request by mandli**
Previously if `gettime` was ever called and the format requested was not `petsc` or `ascii` the code would raise an exception.  Now this checks to see if the file format requested's module contains the function `read_t` and uses that.  Since this routine only cares about time the inconsistent number of variable returned by some of the formats (`binary` in this case) is handled gracefully.  If not `read_t` exists then `None` is returned.

Other fixes:
 - Corrected tabs to spaces and some other spacing issues
 - Addressed the file format specification mentioned in #140 as this bug only appears when file formats are properly handled.

### CODE REVIEW

**Comment by mandli** [comment]
Note that I am not absolutely certain that this is the right thing to do here but seemed like the most obvious solution.

**Comment by ketch** [comment]
It seems to me that the `gettime` function should live in `pyclaw.io`, not in visclaw.

**Comment by mandli** [comment]
That's true and really should be the purpose of the `read_t` functions.  Since this function is not always available I think this was an attempt at getting around that.  Perhaps it would be better to always include even an empty `read_t` although I am not sure if this would work with the PETSc vs. PyClaw IO question.

**Comment by ketch** [comment]
Hmmmm, but why not at least move this function to `src/pyclaw/io/gettime.py`?

**Comment by ketch** [comment]
Of course, if you want to just merge this and perhaps open an issue suggesting that IO stuff like this be migrated in the future, I'm okay with that.

**Comment by mandli** [comment]
I think this makes sense although we would still have to be careful about importing the PETSc IO right?

**Comment by mandli** [comment]
I am all for that.  I think we discussed some of this in #140 as well and just came to the conclusion that VisClaw needs to be disentangled from IO.

**Comment by ketch** [comment]
I think the contents of the function would be exactly the same (i.e., it would still take a format argument).

**Comment by mandli** [comment]
It would be importing `clawpack.petclaw.io` into the namespace of `clawpack.pyclaw.io` but I guess I do not inherently see an issue there.  Should we move this function and see what breaks?

**Comment by ketch** [comment]
Sounds good to me.  

If I understand correctly, the point of this routine is to get the time without reading a whole (possibly huge) outpute file.  I believe there should be a way to get the time from an HDF5 file without reading the whole file, so we should add that at some point.

**Comment by mandli** [comment]
I know we have talked about this before but would something like the following seem reasonable to have as a general purpose object that could handle the common file IO tasks?

```python
class OutputController(object):
    r""""""


    @property
    def file_format(self):
        return self._file_format
    @file_format.setter
    def file_format(self, value):
        if value.lower() == 'petsc':
            self._io_module = __import__("clawpack.petclaw.io.petsc", 
                                   fromlist=["clawpack.petclaw.io"])
            self._file_format = value
        else:
            self._io_module = __import__("clawpack.pyclaw.io.%s" % value, 
                                   fromlist=['clawpack.pyclaw.io'])
            self._file_format = value

        

    def __init__(self, output_path, file_format='ascii'):
        r""""""

        self._io_module = None
        self._file_format = None

        self.output_path = output_path
        self.file_format = file_format


    def get_time(self, frame_num):

        if "read_t" in dir(self._io_module):
            return self._io_module.read_t(frame_num, path=self.output_path)[0]
        else:
            return None
```
I added this to PyClaw while removing (and replacing) the calls to `gettime`.  I am thinking something along these lines could handle what we need to abstract away some of this file format garbage.

**Comment by ketch** [comment]
Yes, that looks good to me.  We can grow this object to let it take over more tasks in the future.  

You can combine the two lines that read

    self._file_format = value

**Comment by mandli** [comment]
I am going to close this PR and open a new one with the proposed changes.  I am not crazy on the name of the module but we can discuss that there.

**Pull request closed without merging**
