### PR TITLE
change patch.grid.c_edges to c_nodes in frametools.py 

### PR DESCRIPTION
**Pull request by rjleveque**
due to clawpack/pyclaw#517.

@mandli, @ketch:  VisClaw broke and I haven't tested everything, but I think this is the only change needed?

### CODE REVIEW

**Comment by ketch** [comment]
After some grepping, I found that spot and no others, so I think you're right.

**Comment by ketch** [comment]
Although it shouldn't be broken -- it should just give a deprecation warning.

**Comment by ketch** [comment]
My mistake -- see https://github.com/clawpack/pyclaw/pull/518.  In any case, it's good that we're updating visclaw to the new names.  We need to update the docs too; I'll do that.  What about the other packages?

**Comment by rjleveque** [comment]
I don't think any other packages would use this.

**Comment by ketch** [comment]
Regarding the docs, it turns out we have no documentation on this outside of docstrings.  I will add some in the future, but we're fine as far as releasing 5.3.0.

**Pull request merged**
