### PR TITLE
Update changes to KML plotting capabilities

### PR DESCRIPTION
**Pull request by donnaaboise**
Updated code that reads in gauges.data file.  Anything after the actual gauge data (t1,t2,x1,x2) is ignored.

### CODE REVIEW

**Comment by mandli** [comment]
The code you wrote (python) looks ok but why not use the Gauges class instead so that if changes are made to the format you won't have to update again?

**Comment by donnaaboise** [comment]
I guess I didn't know there was a gauges class.   Sounds like it would be much simpler.  We'll fix that and reissue the PR.   Thanks.

**Comment by mandli** [comment]
It was added with the changes to the format so probably no reason you would have known.  Let me know if you need help using it.

**Comment by donnaaboise** [comment]
I am closing this PR - Melody fixed the Gauges issue (which now uses the Gauges class) and so that will replace this one.   I'll issue a new one for the Matlab changes.

**Pull request closed without merging**
